# Generated by Django 4.1.5 on 2023-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insection_id', models.CharField(max_length=200)),
                ('insection_date', models.DateTimeField(verbose_name='Date of inspecting')),
            ],
        ),
    ]
