# Generated by Django 4.1.5 on 2023-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_inspectionsource_inspectionstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_in_law',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_of_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.IntegerField(verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
