# Generated by Django 4.1.5 on 2023-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_company_address_alter_company_address_in_law_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionsource',
            name='code',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
