# Generated by Django 4.1.5 on 2023-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_insection_date_inspection_inspection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of inspecting'),
        ),
    ]
