# Generated by Django 4.1.5 on 2023-01-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inspection_inspection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(help_text='ИНН', max_length=200),
        ),
    ]
